import { MediaPack } from './media.types';

/**
 * Resolves an asset path against the document's base href.
 *
 * Using `document.baseURI` rather than a leading slash is what lets the built
 * app work both at a domain root and under a GitHub Pages project subpath,
 * without the paths breaking on deep routes like `/play/maths`.
 */
export function assetUrl(path: string): string {
  return new URL(path, document.baseURI).href;
}

/**
 * The media that ships in the repo. Everything here is generated by
 * `scripts/generate-default-media.ts`, so the game looks and sounds complete on
 * a fresh clone with no API keys.
 */
export function defaultMediaPack(): MediaPack {
  return {
    version: 1,
    activeCharacterId: 'sparkle-fox',
    characters: [
      {
        id: 'sparkle-fox',
        name: 'Sparkle the Fox',
        sheet: {
          src: assetUrl('media/characters/sparkle-fox.svg'),
          cellWidth: 200,
          cellHeight: 200,
          cols: 4,
          rows: 2,
          frameCount: 8,
        },
        animations: {
          idle: { frames: [0, 1], fps: 1.4, loop: true },
          correct: { frames: [2, 3, 3, 2, 3], fps: 6, loop: false },
          wrong: { frames: [4, 5], fps: 2.5, loop: false },
          celebrate: { frames: [6, 7], fps: 5, loop: true },
        },
      },
    ],
    sounds: {
      correct: { src: assetUrl('media/sounds/correct.wav') },
      wrong: { src: assetUrl('media/sounds/wrong.wav'), volume: 0.7 },
      prize: { src: assetUrl('media/sounds/prize.wav') },
      levelUp: { src: assetUrl('media/sounds/levelUp.wav') },
      tap: { src: assetUrl('media/sounds/tap.wav'), volume: 0.5 },
      finish: { src: assetUrl('media/sounds/finish.wav') },
    },
    music: { src: assetUrl('media/music/happy-loop.wav'), volume: 0.3 },
  };
}
